In [ ]:
type Node{T}
    left::Nullable{Node{T}}
    right::Nullable{Node{T}}
    value::T
end

Node{T}(v::T) = Node(Nullable{Node{T}}(), Nullable{Node{T}}(), v)

In [1]:
n1 = Node(Nullable(Node(2)), Nullable(Node(3)), 10)

LoadError: LoadError: UndefVarError: Node not defined
while loading In[1], in expression starting on line 1

In [12]:
left(n::Node) = isnull(n.left) ? Void(): get(n.left)
right(n::Node) = isnull(n.right) ? Void(): get(n.right)

right (generic function with 1 method)

In [ ]:
function search{T}(graph::Node{T}, number)
    for i = 1:10
        if graph.value == number
            return number
        else
            try
                graph = graph.left.value
            catch
                return 0
            end
        end
    end
end
    

In [1]:
include("SymmetricMatrix.jl")
include("Test.jl")
using Test

In [2]:
include("SymmetricMatrix.jl")
using SymmetricMatrix
using NullableArrays
importall SymmetricMatrix

genstensor (generic function with 2 methods)

In [4]:
l = 75
st = genstensor(Float64, 4,l);
st1 = genstensor(Float64, 4,l, 1233);
c = randn(l,12);

In [5]:
bs = (convert(BoxStructure{Float64}, st, 10)) ;
@time bs1 = (convert(BoxStructure{Float64}, st1, 10)) ;

  0.368854 seconds (320.15 k allocations: 589.424 MB, 32.72% gc time)


In [6]:
@time bs+bs1;
@time bs+2;
@time st + st1;
@time st + 2;

  0.107971 seconds (259.60 k allocations: 13.942 MB)
  0.080173 seconds (322.12 k allocations: 17.625 MB, 4.54% gc time)
  0.013778 seconds (7 allocations: 47.684 MB, 19.70% gc time)
  0.012109 seconds (7 allocations: 47.684 MB, 10.60% gc time)


In [7]:
@time convert(Array{Float64}, bs);
@time vec(bs);
@time vec(st);

  0.338190 seconds (1.23 M allocations: 148.155 MB, 15.07% gc time)
  0.297563 seconds (1.21 M allocations: 147.300 MB, 15.78% gc time)
  0.000001 seconds (6 allocations: 240 bytes)


In [8]:
@time bs.*bs1;
@time bs+bs1;
@time bs./bs1;
@time st.*st1;
@time st+st1;
@time st./st1;

  0.046923 seconds (217.14 k allocations: 12.077 MB, 5.30% gc time)
  0.041683 seconds (211.89 k allocations: 11.764 MB)
  0.046537 seconds (217.14 k allocations: 12.077 MB, 5.47% gc time)
  0.018239 seconds (13 allocations: 47.684 MB, 7.72% gc time)
  0.015898 seconds (7 allocations: 47.684 MB, 4.35% gc time)
  0.049982 seconds (13 allocations: 47.684 MB, 1.66% gc time)


In [8]:
@time modemult(bs, c', 4)
@time Tensors.modemult(st,c',4);

  3.900043 seconds (5.54 M allocations: 6.035 GB, 6.03% gc time)
  1.293228 seconds (176 allocations: 946.063 MB, 2.76% gc time)


In [3]:
using Tensors
using NullableArrays
using Iterators
using Base.size

using Iterators
function genstensor(T::Type, dims::Int, l::Int, seed::Int = 1234)
    srand(seed)
    ret = zeros(T, fill(l, dims)...)
    indices = collect(product(fill(collect(1:l), dims)...))
    elements = Array{T,1}(randn(l^dims÷dims))
    r = 1
    for i in indices 
        if issorted(i)          
            for k in collect(permutations(i))
                ret[k...] = elements[r]
            end
            r += 1
        end
    end
    ret
end

T1 = randn(5,5);
r = randn(13,13)
r1 = randn(13,10)
c = covbs(r, 2);
c1 = cov(r, corrected = false);



In [5]:
t = genstensor(Float64, 4,13)
bs = convert(BoxStructure{Float64}, t, 3);

In [31]:
function bcss1{T <: AbstractFloat, N}(bsdata::BoxStructure{T, N}, m::Matrix{T})
    s = size(bsdata)
    s[3]  == size(m,1)||throw(DimensionMismatch("size of B1 $(s[3]) must equal to size of A $(size(m,1))"))
    m = slise(m, s[1])
    ret = NullableArray(Array{T, 2}, size(m,2), size(m,2))
    for j = 1:size(m,2), i = 1:j
        temp = NullableArray(Array{T, 2}, s[2], 1)
        for k = 1:s[2]
            temp[k, 1] = segmentmult([k,j], bsdata, m)
        end
        ret[i,j] = segmentmult([i,1], m, temp)
    end
    BoxStructure(ret)
end


bcss1 (generic function with 1 method)

In [4]:
bcss1(c, r1);

In [5]:
bcss(c, r1) - bcss1(c, r1)

SymmetricMatrix.BoxStructure{Float64,2}(NullableArrays.NullableArray{Array{Float64,2},2}[
5x5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0,

#NULL,
5x5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0,

5x5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0],5)

In [9]:
for f in (
    :+,
    :-,
)
    @eval begin
        @inline function $(f){S1, S2}(x::Nullable{Matrix{S1}}, y::Nullable{Matrix{S2}}, i::Int)
            Nullable($(f)(x.value, y.value), x.isnull | y.isnull)
        end
    end
end


In [3]:
r = randn(7,7)
a = covbs(r);


In [6]:
a*0

SymmetricMatrix.BoxStructure{Float64,2}(NullableArrays.NullableArray{Array{Float64,2},2}[
3x3 Array{Float64,2}:
  0.0  -0.0   0.0
 -0.0   0.0  -0.0
  0.0  -0.0   0.0,

#NULL,#NULL,
3x3 Array{Float64,2}:
  0.0  -0.0   0.0
 -0.0   0.0  -0.0
  0.0  -0.0   0.0,

3x3 Array{Float64,2}:
  0.0  -0.0  -0.0
 -0.0   0.0  -0.0
 -0.0  -0.0   0.0,

#NULL,
3x1 Array{Float64,2}:
 0.0
 0.0
 0.0,

3x1 Array{Float64,2}:
 -0.0
 -0.0
  0.0,

1x1 Array{Float64,2}:
 0.0],3)

In [8]:
*(a, 0, true)


SymmetricMatrix.BoxStructure{Float64,2}(NullableArrays.NullableArray{Array{Float64,2},2}[
3x3 Array{Float64,2}:
  0.0  -0.0   0.0
 -0.0   0.0  -0.0
  0.0  -0.0   0.0,

#NULL,#NULL,
3x3 Array{Float64,2}:
  0.0  -0.0   0.0
 -0.0   0.0  -0.0
  0.0  -0.0   0.0,

3x3 Array{Float64,2}:
  0.0  -0.0  -0.0
 -0.0   0.0  -0.0
 -0.0  -0.0   0.0,

#NULL,
3x1 Array{Float64,2}:
 0.0
 0.0
 0.0,

3x1 Array{Float64,2}:
 -0.0
 -0.0
  0.0,

1x1 Array{Float64,2}:
 0.0],3)

In [9]:
a

SymmetricMatrix.BoxStructure{Float64,2}(NullableArrays.NullableArray{Array{Float64,2},2}[
3x3 Array{Float64,2}:
  0.0  -0.0   0.0
 -0.0   0.0  -0.0
  0.0  -0.0   0.0,

#NULL,#NULL,
3x3 Array{Float64,2}:
  0.0  -0.0   0.0
 -0.0   0.0  -0.0
  0.0  -0.0   0.0,

3x3 Array{Float64,2}:
  0.0  -0.0  -0.0
 -0.0   0.0  -0.0
 -0.0  -0.0   0.0,

#NULL,
3x1 Array{Float64,2}:
 0.0
 0.0
 0.0,

3x1 Array{Float64,2}:
 -0.0
 -0.0
  0.0,

1x1 Array{Float64,2}:
 0.0],3)

In [3]:
+!(2,2)

LoadError: LoadError: MethodError: `!` has no method matching !(::Int64, ::Int64)
while loading In[3], in expression starting on line 1